---
pl:
  simple_form:
    hints:
      defaults:
        setting_skin: Zmienia wygląd używanej odmiany koyu.spacea
    labels:
      defaults:
        setting_favourite_modal: Pytaj o potwierdzenie przed dodaniem do ulubionych
        setting_skin: Motyw
